const Project = [
  {
    id: "d",
    projectDescription:
      "Made a Windows XP themed Portfolio, with features such as restart and switch off.",
    projectName: "Weather.io",
    github: "https://github.com/ujjwalpathaak/Weather.io---WebApp",
    website: "",
    imgURL:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgICAgIBwcGBwcIBwoIBwcHBw8ICQcKFREWIhURExMYHSggGCYlJxMTITEhJSkrLi4uFx8zODMsNyg5LisBCgoKDg0OFw8PDysZFR0tLSstNy0rKystKystKy0rKzcrLSsrKysrKysrKy0rKysrKysrKy03KysrKysrKysrK//AABEIASsAqAMBIgACEQEDEQH/xAAYAAEBAQEBAAAAAAAAAAAAAAAAAQIDB//EABwQAQEBAAIDAQAAAAAAAAAAAAABEQIhAzFBsf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwD3EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABm1pP0FAAAAAAAAAAAAABKoAAAAkBWWgAAAAAAAAAAAAAEBQAAAAAAAAAAAAAAAAAAAAAAABIoAAAAAAAAAAAAAAAAAACVQAABPqpICgAAAAAAAAAAAAAAAAAAAAAAAAAkUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACfVSe1AAAAAAAAAAAAAAAAAAABKBFAAAAAAEoAluS04Ca0AKAAAAAAAAIoAAAAAAAigMc5sxrjMigmAAoAAAAAAAAAAAAAAAACW4CjnfJGpQaGd7aAAAAAAAAAAAAAAAAAY576jaYJXHj4++3XMjQEmOXHddUkVIoAoAAAAAAAAAAAAAAAAJVSgkaSKAAAAAAD/9k=",
  },
  {
    id: "b",
    projectDescription:
      "Made a Windows XP themed Portfolio, with features such as restart and switch off.",
    projectName: "Sudoku Solver",
    github: "https://github.com/ujjwalpathaak/Sudoku_Solver",
    website: "",
    imgURL:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgICAgIBwcGBwcIBwoIBwcHBw8ICQcKFREWIhURExMYHSggGCYlJxMTITEhJSkrLi4uFx8zODMsNyg5LisBCgoKDg0OFw8PDysZFR0tLSstNy0rKystKystKy0rKzcrLSsrKysrKysrKy0rKysrKysrKy03KysrKysrKysrK//AABEIASsAqAMBIgACEQEDEQH/xAAYAAEBAQEBAAAAAAAAAAAAAAAAAQIDB//EABwQAQEBAAIDAQAAAAAAAAAAAAABEQIhAzFBsf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwD3EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABm1pP0FAAAAAAAAAAAAABKoAAAAkBWWgAAAAAAAAAAAAAEBQAAAAAAAAAAAAAAAAAAAAAAABIoAAAAAAAAAAAAAAAAAACVQAABPqpICgAAAAAAAAAAAAAAAAAAAAAAAAAkUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACfVSe1AAAAAAAAAAAAAAAAAAABKBFAAAAAAEoAluS04Ca0AKAAAAAAAAIoAAAAAAAigMc5sxrjMigmAAoAAAAAAAAAAAAAAAACW4CjnfJGpQaGd7aAAAAAAAAAAAAAAAAAY576jaYJXHj4++3XMjQEmOXHddUkVIoAoAAAAAAAAAAAAAAAAJVSgkaSKAAAAAAD/9k=",
  },
  {
    id: "a",
    projectDescription:
      "Made a Windows XP themed Portfolio, with features such as restart and switch off.",
    projectName: "Windows-XP Themed Portfolio",
    github: "https://github.com/ujjwalpathaak/WindowsXP_Portfolio",
    website: "",
    imgURL:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgICAgIBwcGBwcIBwoIBwcHBw8ICQcKFREWIhURExMYHSggGCYlJxMTITEhJSkrLi4uFx8zODMsNyg5LisBCgoKDg0OFw8PDysZFR0tLSstNy0rKystKystKy0rKzcrLSsrKysrKysrKy0rKysrKysrKy03KysrKysrKysrK//AABEIASsAqAMBIgACEQEDEQH/xAAYAAEBAQEBAAAAAAAAAAAAAAAAAQIDB//EABwQAQEBAAIDAQAAAAAAAAAAAAABEQIhAzFBsf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwD3EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABm1pP0FAAAAAAAAAAAAABKoAAAAkBWWgAAAAAAAAAAAAAEBQAAAAAAAAAAAAAAAAAAAAAAABIoAAAAAAAAAAAAAAAAAACVQAABPqpICgAAAAAAAAAAAAAAAAAAAAAAAAAkUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACfVSe1AAAAAAAAAAAAAAAAAAABKBFAAAAAAEoAluS04Ca0AKAAAAAAAAIoAAAAAAAigMc5sxrjMigmAAoAAAAAAAAAAAAAAAACW4CjnfJGpQaGd7aAAAAAAAAAAAAAAAAAY576jaYJXHj4++3XMjQEmOXHddUkVIoAoAAAAAAAAAAAAAAAAJVSgkaSKAAAAAAD/9k=",
  },
  {
    id: "c",
    projectDescription:
      "Made a Windows XP themed Portfolio, with features such as restart and switch off.",
    projectName: "AnuvJain Portfolio",
    github: "https://github.com/ujjwalpathaak/Anuv_Jain-Portfolio",
    website: "",
    imgURL:
      "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgICAgIBwcGBwcIBwoIBwcHBw8ICQcKFREWIhURExMYHSggGCYlJxMTITEhJSkrLi4uFx8zODMsNyg5LisBCgoKDg0OFw8PDysZFR0tLSstNy0rKystKystKy0rKzcrLSsrKysrKysrKy0rKysrKysrKy03KysrKysrKysrK//AABEIASsAqAMBIgACEQEDEQH/xAAYAAEBAQEBAAAAAAAAAAAAAAAAAQIDB//EABwQAQEBAAIDAQAAAAAAAAAAAAABEQIhAzFBsf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAAER/9oADAMBAAIRAxEAPwD3EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABm1pP0FAAAAAAAAAAAAABKoAAAAkBWWgAAAAAAAAAAAAAEBQAAAAAAAAAAAAAAAAAAAAAAABIoAAAAAAAAAAAAAAAAAACVQAABPqpICgAAAAAAAAAAAAAAAAAAAAAAAAAkUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACfVSe1AAAAAAAAAAAAAAAAAAABKBFAAAAAAEoAluS04Ca0AKAAAAAAAAIoAAAAAAAigMc5sxrjMigmAAoAAAAAAAAAAAAAAAACW4CjnfJGpQaGd7aAAAAAAAAAAAAAAAAAY576jaYJXHj4++3XMjQEmOXHddUkVIoAoAAAAAAAAAAAAAAAAJVSgkaSKAAAAAAD/9k=",
  },
];

export default Project;
